services:
  warden:
    build: .
    container_name: warden-auth-cli
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - db_data:/app/data
      - log_data:/app/logs
    restart: unless-stopped

volumes:
  db_data:
  log_data: